#!/usr/bin/env python

"""Deletes a me environment

Usage:
  delete_env --env_name <env_name>

Options:
  -h --help              Show this help
  --env_name <env_name>  The name of the environment to delete

"""

from docopt import docopt
import pdb
from deployment import Deployment

if __name__ == '__main__':
    arguments = docopt(__doc__)

Deployment(arguments["--env_name"]).delete()

